[package]
name = "fhe_auction"
type = "contract"
authors = [""]
compiler_version = ">=0.18.0"

[dependencies]
aztec = { git="https://github.com/AztecProtocol/aztec-packages/", tag="aztec-packages-v0.15.0", directory="yarn-project/aztec-nr/aztec" }
lwe = { path = "../lwe-noir/" }